require("plugins")
require("mason-config") -- This needs to be before the lsp configuration
require("formatter-config")
require("lint-config")
require("treesitter")
require("statusbar")
require("filetree")
require("keybindings")
require("options")
require("colorscheme")
